name = "durable-objects-template"
main = "index.mjs"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "MAILBOX_DO"
# ğŸš¨ æ£€æŸ¥è¿™é‡Œï¼å¿…é¡»æ˜¯ MailboxDOV2
class_name = "MailboxDOV2" 

[[migrations]]
# ğŸš¨ æ£€æŸ¥è¿™é‡Œï¼tag æ¢æˆä¸€ä¸ªå…¨æ–°çš„ v100
tag = "v100" 
# ğŸš¨ æ£€æŸ¥è¿™é‡Œï¼å¿…é¡»æ˜¯ MailboxDOV2
new_sqlite_classes = ["MailboxDOV2"] 
