name = "durable-objects-template"
main = "src/index.mjs"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "COUNTER"
class_name = "MailboxDO"

[[migrations]]
tag = "v3" # ğŸš¨ æ”¹æˆ v3ï¼Œç¡®ä¿è§¦å‘æ–°è¿ç§»
new_sqlite_classes = ["MailboxDO"] # ğŸš¨ å…³é”®ï¼šæŠŠ new_classes æ”¹æˆ new_sqlite_classes
