name = "durable-objects-template"
main = "src/index.mjs"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "MAILBOX_DO"   # è¿™ä¸ªä¸è¦åŠ¨
class_name = "MailboxDOV2"  # ğŸ‘ˆ å¿…é¡»æ”¹ï¼

[[migrations]]
tag = "v100"  # ğŸ‘ˆ è·³ä¸ªå¤§å·ï¼Œé˜²æ­¢å’Œæ—§è®°å½•æ’è½¦
new_sqlite_classes = ["MailboxDOV2"]  # ğŸ‘ˆ å¿…é¡»æ”¹ï¼
