name = "durable-objects-template"
main = "index.mjs"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "MAILBOX_DO"
class_name = "MailboxDO"

[[migrations]]
tag = "v1" # 重新从 v1 开始
new_sqlite_classes = ["MailboxDO"]
